write_data = input("Enter text to write to the file: ")
o1=open('output.txt','w')
o1.write(write_data)
o1.close()
print("Data successfuly written to output.txt\n")
append_data = input("Enter additional text to append to the file: ")
o1=open('output.txt','a')
o1.write('\n' +append_data)
o1.close()
print("Data successfully appended\n")
o1=open('output.txt','r')
output=o1.read()
o1.close()
print("Final content of output.txt: ")
print(output)